---
language: go
go:
- 1.9.x
- 1.10.x

install:
- go get -v -t ./...
- go get honnef.co/go/tools/cmd/unused
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/onsi/ginkgo/ginkgo
- go get -u github.com/onsi/gomega/...
- export PATH=$PATH:$HOME/gopath/bin
