---
language: go
go:
- 1.9.x
- 1.10.x

install:
- go get -v -t ./...
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/onsi/ginkgo/ginkgo
- go get -u github.com/onsi/gomega/...
- export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace && \
        for DIR in $(find . -type f -name "*.go" -exec dirname {} \; | grep -v vendor | sort -u); do ( cd $DIR && go vet ); done
